project:
  type: website
  output-dir: ../docs

website:
  title: "松浦プレゼミのウェブサイト"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: presemi2024.qmd
        text: プレゼミ

format:
  html:
    theme: pulse
    html-math-method: katex



code-block-bg: "#F6F6F6"
mainfont: "Hiragino Mincho ProN"
execute:
  echo : TRUE
  message : FALSE
  warning: FALSE
  error: FALSE
  fig-width: 10
  fig-height: 6

lang: "ja"
# server: shiny
monofontoptions:
  - Scale = .5

# Set default options for every bookpage that may or may not include webR.
webr:
  # show-startup-message: false    # Disable displaying status of webR initialization
  packages: ['ggplot2', 'ggthemes','dplyr'] # Install R packages on document open

# Attach webR extension for the project
filters:
  - webr